# Generated by Django 2.1.8 on 2019-04-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titlte',
            new_name='title',
        ),
    ]
