# Generated by Django 2.1.8 on 2019-04-25 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190425_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20, message='미성년자는 노노')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='이메일 형식에 맞지 않습니다.')]),
        ),
    ]
